server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dashboard
    driver-class-name: org.mariadb.jdbc.Driver
    username: ingyu
    password: kang

  data:
    web:
      pageable:
        default-page-size: 20

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

    hibernate:
      ddl-auto: create

    open-in-view: true


  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB



  profiles:
    include: jwt

springdoc:
  packages-to-scan: kig.dashboard
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs
  paths-to-match:
      - /api/**


logging:
  level:
    org:

      hibernate:
        SQL: debug

file:
  dir: C:\Users\Administrator\Desktop\tmp\

