spring:

#  datasource:

  data:
    web:
      pageable:
        default-page-size: 20

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

    hibernate:
      ddl-auto: none

    open-in-view: false


  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB



  profiles:
    include: jwt



logging:
  level:
    org:

      hibernate:
        SQL: debug

file:
  dir: C:\Users\Administrator\Desktop\tmp\

